export const PROVINCE_TH = [
  'กรุงเทพฯ',
  'กระบี่',
  'กาญจนบุรี',
  'กาฬสินธุ์',
  'กำแพงเพชร',
  'ขอนแก่น',
  'จันทบุรี',
  'ฉะเชิงเทรา',
  'ชลบุรี',
  'ชัยนาท',
  'ชัยภูมิ',
  'ชุมพร',
  'เชียงใหม่',
  'เชียงราย',
  'ตรัง',
  'ตราด',
  'ตาก',
  'นครนายก',
  'นครปฐม',
  'นครพนม',
  'นครราชสีมา',
  'นครศรีธรรมราช',
  'นครสวรรค์',
  'นนทบุรี',
  'นราธิวาส',
  'น่าน',
  'บึงกาฬ',
  'บุรีรัมย์',
  'ปทุมธานี',
  'ประจวบคีรีขันธ์',
  'ปราจีนบุรี',
  'ปัตตานี',
  'พระนครศรีอยุธยา',
  'พะเยา',
  'พังงา',
  'พัทลุง',
  'พิจิตร',
  'พิษณุโลก',
  'เพชรบุรี',
  'เพชรบูรณ์',
  'แพร่',
  'ภูเก็ต',
  'มหาสารคาม',
  'มุกดาหาร',
  'แม่ฮ่องสอน',
  'ยโสธร',
  'ยะลา',
  'ร้อยเอ็ด',
  'ระนอง',
  'ระยอง',
  'ราชบุรี',
  'ลพบุรี',
  'ลำปาง',
  'ลำพูน',
  'เลย',
  'ศรีสะเกษ',
  'สกลนคร',
  'สงขลา',
  'สตูล',
  'สมุทรปราการ',
  'สมุทรสงคราม',
  'สมุทรสาคร',
  'สระแก้ว',
  'สระบุรี',
  'สิงห์บุรี',
  'สุโขทัย',
  'สุพรรณบุรี',
  'สุราษฎร์ธานี',
  'สุรินทร์',
  'หนองคาย',
  'หนองบัวลำภู',
  'อ่างทอง',
  'อำนาจเจริญ',
  'อุดรธานี',
  'อุตรดิตถ์',
  'อุทัยธานี',
  'อุบลราชธานี',
];

export const PROVINCE_TH_MAP = {
  'krabi': 'กระบี่',
  'bangkok': 'กรุงเทพมหานคร',
  'kanchanaburi': 'กาญจนบุรี',
  'kalasin': 'กาฬสินธุ์',
  'kamphaengphet': 'กำแพงเพชร',
  'khonkaen': 'ขอนแก่น',
  'chanthaburi': 'จันทบุรี',
  'chachoengsao': 'ฉะเชิงเทรา',
  'chonburi': 'ชลบุรี',
  'chainat': 'ชัยนาท',
  'chaiyaphum': 'ชัยภูมิ',
  'chumphon': 'ชุมพร',
  'chiangrai': 'เชียงราย',
  'chiangmai': 'เชียงใหม่',
  'trang': 'ตรัง',
  'trat': 'ตราด',
  'tak': 'ตาก',
  'nakhonnayok': 'นครนายก',
  'nakhonpathom': 'นครปฐม',
  'nakhonphanom': 'นครพนม',
  'nakhonratchasima': 'นครราชสีมา',
  'nakhonsithammarat': 'นครศรีธรรมราช',
  'nakhonsawan': 'นครสวรรค์',
  'nonthaburi': 'นนทบุรี',
  'narathiwat': 'นราธิวาส',
  'nan': 'น่าน',
  'buriram': 'บุรีรัมย์',
  'pathumthani': 'ปทุมธานี',
  'prachuapkhirikhan': 'ประจวบคีรีขันธ์',
  'prachinburi': 'ปราจีนบุรี',
  'pattani': 'ปัตตานี',
  'ayutthaya': 'พระนครศรีอยุธยา',
  'phayao': 'พะเยา',
  'phangnga': 'พังงา',
  'phatthalung': 'พัทลุง',
  'phichit': 'พิจิตร',
  'phitsanulok': 'พิษณุโลก',
  'phetchaburi': 'เพชรบุรี',
  'phetchabun': 'เพชรบูรณ์',
  'phrae': 'แพร่',
  'phuket': 'ภูเก็ต',
  'mahasarakham': 'มหาสารคาม',
  'mukdahan': 'มุกดาหาร',
  'maehongson': 'แม่ฮ่องสอน',
  'yasothon': 'ยโสธร',
  'yala': 'ยะลา',
  'roiet': 'ร้อยเอ็ด',
  'ranong': 'ระนอง',
  'rayong': 'ระยอง',
  'ratchaburi': 'ราชบุรี',
  'lopburi': 'ลพบุรี',
  'loei': 'เลย',
  'lampang': 'ลำปาง',
  'lamphun': 'ลำพูน',
  'sisaket': 'ศรีสะเกษ',
  'sakonnakhon': 'สกลนคร',
  'songkhla': 'สงขลา',
  'satun': 'สตูล',
  'samutprakan': 'สมุทรปราการ',
  'samutsongkhram': 'สมุทรสงคราม',
  'samutsakhon': 'สมุทรสาคร',
  'sakaeo': 'สระแก้ว',
  'saraburi': 'สระบุรี',
  'singburi': 'สิงห์บุรี',
  'sukhothai': 'สุโขทัย',
  'suphanburi': 'สุพรรณบุรี',
  'suratthani': 'สุราษฎร์ธานี',
  'surin': 'สุรินทร์',
  'nongkhai': 'หนองคาย',
  'nongbualamphu': 'หนองบัวลำภู',
  'angthong': 'อ่างทอง',
  'amnatcharoen': 'อำนาจเจริญ',
  'udonthani': 'อุดรธานี',
  'uttaradit': 'อุตรดิตถ์',
  'uthaithani': 'อุทัยธานี',
  'ubonratchathani': 'อุบลราชธานี',
  'betong': 'เบตง'
};

export const PROVINCE_TH_TO_ENG = {
  "กระบี่": "krabi",
  "กรุงเทพมหานคร": "bangkok",
  "กาญจนบุรี": "kanchanaburi",
  "กาฬสินธุ์": "kalasin",
  "กำแพงเพชร": "kamphaengphet",
  "ขอนแก่น": "khonkaen",
  "จันทบุรี": "chanthaburi",
  "ฉะเชิงเทรา": "chachoengsao",
  "ชลบุรี": "chonburi",
  "ชัยนาท": "chainat",
  "ชัยภูมิ": "chaiyaphum",
  "ชุมพร": "chumphon",
  "เชียงราย": "chiangrai",
  "เชียงใหม่": "chiangmai",
  "ตรัง": "trang",
  "ตราด": "trat",
  "ตาก": "tak",
  "นครนายก": "nakhonnayok",
  "นครปฐม": "nakhonpathom",
  "นครพนม": "nakhonphanom",
  "นครราชสีมา": "nakhonratchasima",
  "นครศรีธรรมราช": "nakhonsithammarat",
  "นครสวรรค์": "nakhonsawan",
  "นนทบุรี": "nonthaburi",
  "นราธิวาส": "narathiwat",
  "น่าน": "nan",
  "บุรีรัมย์": "buriram",
  "ปทุมธานี": "pathumthani",
  "ประจวบคีรีขันธ์": "prachuapkhirikhan",
  "ปราจีนบุรี": "prachinburi",
  "ปัตตานี": "pattani",
  "พระนครศรีอยุธยา": "ayutthaya",
  "พะเยา": "phayao",
  "พังงา": "phangnga",
  "พัทลุง": "phatthalung",
  "พิจิตร": "phichit",
  "พิษณุโลก": "phitsanulok",
  "เพชรบุรี": "phetchaburi",
  "เพชรบูรณ์": "phetchabun",
  "แพร่": "phrae",
  "ภูเก็ต": "phuket",
  "มหาสารคาม": "mahasarakham",
  "มุกดาหาร": "mukdahan",
  "แม่ฮ่องสอน": "maehongson",
  "ยโสธร": "yasothon",
  "ยะลา": "yala",
  "ร้อยเอ็ด": "roiet",
  "ระนอง": "ranong",
  "ระยอง": "rayong",
  "ราชบุรี": "ratchaburi",
  "ลพบุรี": "lopburi",
  "เลย": "loei",
  "ลำปาง": "lampang",
  "ลำพูน": "lamphun",
  "ศรีสะเกษ": "sisaket",
  "สกลนคร": "sakonnakhon",
  "สงขลา": "songkhla",
  "สตูล": "satun",
  "สมุทรปราการ": "samutprakan",
  "สมุทรสงคราม": "samutsongkhram",
  "สมุทรสาคร": "samutsakhon",
  "สระแก้ว": "sakaeo",
  "สระบุรี": "saraburi",
  "สิงห์บุรี": "singburi",
  "สุโขทัย": "sukhothai",
  "สุพรรณบุรี": "suphanburi",
  "สุราษฎร์ธานี": "suratthani",
  "สุรินทร์": "surin",
  "หนองคาย": "nongkhai",
  "หนองบัวลำภู": "nongbualamphu",
  "อ่างทอง": "angthong",
  "อำนาจเจริญ": "amnatcharoen",
  "อุดรธานี": "udonthani",
  "อุตรดิตถ์": "uttaradit",
  "อุทัยธานี": "uthaithani",
  "อุบลราชธานี": "ubonratchathani",
  "เบตง": "betong",
  "": ""
}